// <auto-generated />
using System;
using HMS.PatientRegistration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS.PatientRegistration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatientRegistrationDbContext))]
    partial class PatientRegistrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMS.PatientRegistration.Domain.Entities.DropdownItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "ParentCode");

                    b.ToTable("DropdownItems", (string)null);
                });

            modelBuilder.Entity("HMS.PatientRegistration.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeDays")
                        .HasColumnType("int");

                    b.Property<int?>("AgeMonths")
                        .HasColumnType("int");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BloodGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaritalStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MrNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientType")
                        .HasColumnType("int");

                    b.Property<string>("PrefixCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefixName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MrNumber");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("HMS.PatientRegistration.Domain.Entities.Patient", b =>
                {
                    b.OwnsOne("HMS.PatientRegistration.Domain.Entities.AdditionalDetails", "AdditionalDetails", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("NationalityCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NationalityName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PreferredLanguageCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PreferredLanguageName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RaceCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RaceName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReligionCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReligionName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WarningAlerts")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("HMS.PatientRegistration.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AreaCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AreaName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CityCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CityName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CountryName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("PhoneCountryCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Pincode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StateCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StateName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StdCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("HMS.PatientRegistration.Domain.Entities.ProfessionalDetails", "ProfessionalDetails", b1 =>
                        {
                            b1.Property<int>("PatientId")
                                .HasColumnType("int");

                            b1.Property<string>("CompanyCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CompanyName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("IncomeCategoryCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("IncomeCategoryName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("OccupationCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("OccupationName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProfessionCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProfessionName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("AdditionalDetails")
                        .IsRequired();

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ProfessionalDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
